FROM python:3.11-alpine AS builder

WORKDIR /app
COPY app/requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

FROM python:3.11-alpine

WORKDIR /app

COPY --from=builder /install /usr/local
COPY app/ .

RUN adduser -D appuser && chown -R appuser /app
USER appuser

CMD ["python", "main.py"]