FROM python:3.11-alpine

WORKDIR /app

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .

RUN adduser -D appuser && chown -R appuser /app
USER appuser

CMD ["python", "main.py"]